### ISSUE TITLE
Add search to EmojiPicker

### ISSUE THREAD

**Issue by tapkain** [Fintasys/emoji_picker_flutter#130]
Hello, it would be nice to have a search bar in the EmojiPicker

**Comment by LostInDarkMath** [comment]
Does https://github.com/Fintasys/emoji_picker_flutter/pull/96 is what you are looking for?

**Comment by tapkain** [comment]
yes, it has the example, missed that. I guess there is a reason why search can't be added to the EmojiPicker and needs to be implemented on the user side?

**Comment by Fintasys** [comment]
Well, it's not that we can't or we won't. It's just there are many ways to implement a search based on the app and design. The reason because we haven't provided a standard solution yet is basically just lack of time. With the example we wanted to show a way how to do it if someone needs it. But probably still needs some adjustments case by case.

**Comment by tapkain** [comment]
gotcha, thank you guys for pointing out.
