### ISSUE TITLE
[Feature] Filter out emojis that cannot be displayed on iOS

### ISSUE THREAD

**Issue by naamapps** [Fintasys/emoji_picker_flutter#165]
Hi,
Thanks for the great package.
I was wondering if it's possible to filter out unsupported emojis on iOS.
I know it's currently only for android. But there is not reason why.

Please consider adding it to the package,
Thanks!

**Comment by Fintasys** [comment]
iOS doesn't provide an easy way to determine which emoji is supported or not like Android does. Beside that all emoji should be supported by iOS. Is there anything that doesn't work?

**Comment by naamapps** [comment]
@Fintasys Thanks for your super quick response!
Well for older iOS versions not all emojis are supported (which is to be expected).
I hope we can come up with a workaround, because looking at question marks is super bad UX.
See iOS 15.3.1:

![IMG_0272](https://github.com/Fintasys/emoji_picker_flutter/assets/37176893/ead13f7d-9ff4-4669-8cd6-8841738dc49c)

**Comment by stact** [comment]
It's seems the issue is related to flutter. 
Several issue are still opened:
* https://github.com/flutter/flutter/issues/49627
* https://github.com/flutter/flutter/issues/36062

I tried to check but there is no easy way to detect this glitch. 
We have also this option `checkPlatformCompatibility` but it seems is still displaying the unsupported emojis :)

Any idea?

**Comment by stact** [comment]
@Fintasys I found a good workaround. No more glitch :)
Regarding this comment: https://github.com/flutter/flutter/issues/49627#issuecomment-1265222623

We can have this config (maybe it could be nice to have it by default in your package)

```dart

config: const Config(
  emojiTextStyle: TextStyle(
    fontFamilyFallback: [
      'Apple Color Emoji',
      'Noto Color Emoji',
    ],
  ),
),
```
